export const ActionTypes = {
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
	FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
	FETCH_USERS_FROM_STORE: 'FETCH_USERS_FROM_STORE',
	UPDATE_USER: 'UPDATE_USER',
	DELETE_USER: 'DELETE_USER',
	FETCH_VENUES_SUCCESS: 'FETCH_VENUES_SUCCESS',
	FETCH_VENUES_FAILURE: 'FETCH_VENUES_FAILURE',
	FETCH_VENUES_FROM_STORE: 'FETCH_VENUES_FROM_STORE'
};

